apiVersion: v1
kind: Service
metadata:
  name: patients
  labels:
    app: patients
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: patients
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  name: patients
spec:
  rules:
  - host: rublag.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: patients
          servicePort: 80
  - host: www.rublag.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: patients
          servicePort: 80
  tls:
  - hosts:
    - rublag.xyz
    - www.rublag.xyz
    secretName: rublag-xyz-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients
  labels:
    app: patients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients
  template:
    metadata:
      labels:
        app:
          patients
    spec:
      containers:
      - name: patients
        image: rublagns/patients:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub
