name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    - name: Build uberjar image
      run: lein uberjar
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker container and publish to Github Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rublagns/patients:latest
    - name: Create Kube config from secret
      env:
        KUBE_CONFIG_TEXT: ${{ secrets.KUBE_CONFIG_TEXT }}
      run: echo $KUBE_CONFIG_TEXT | base64 -d > kubeconfig.yaml
    - name: Deploy
      run: kubectl --kubeconfig kubeconfig.yaml replace -f patients.yaml --force
